name: saletrackerapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.4
  intl: ^0.17.0
  pdf: ^3.3.0
  rive: ^0.7.12
  mailto: ^2.0.0
  url_launcher: ^6.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.2.0
  google_sign_in: ^5.0.4
  cloud_firestore: ^5.0.1
  flutter_slidable: ^0.6.0
  flutter_file_dialog: ^2.1.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/res/pattern_back.jpg
    - lib/res/portable-table.riv
    - lib/res/RobotoSlab-Bold.ttf
    - lib/res/RobotoSlab-Light.ttf
    - lib/res/RobotoSlab-Regular.ttf

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/res/RobotoSlab-Regular.ttf
        - asset: lib/res/RobotoSlab-Bold.ttf
          weight: 700
        - asset: lib/res/RobotoSlab-Light.ttf
          weight: 300
